channels:
  - pytorch
  - defaults
dependencies:
  - pip
  - protobuf
  - pip:
    - hypothesis
    - future
    - cloudpickle
    - pytest
    - pytest-benchmark
    - pytest-cov
    - pytest-mock
    - pytest-instafail
    - pytest-rerunfailures
    - pytest-timeout
    - expecttest
    - coverage
    - h5py
    - orjson
    - numpy<2.0.0
